### PR TITLE
images now have clickable crosshair and x,y coordinates

### PR DESCRIPTION
**Pull request by aransfor**

### CODE REVIEW

**Comment by aransfor** [comment]
@urbaneg not sure if you use the grapher to view saved images but this makes those tabs mimic the andor video server functionality for clicking the crosshair and axis display

**Comment by dachichian** [comment]
Do you mean images like pulling up old data or do you mean actually pulling up image files in the grapher? If so, I don't think we've ever done that.  In what context have you found that useful?

**Comment by urbaneg** [comment]
That last comment was actually from me. I didn't notice that someone else had logged into github from my computer.

**Comment by aransfor** [comment]
we are doing some experiments where save images from the camera of the ion spread and we look at these images that are saved with the dv.save_image function. RSG already does this but it doesnt have the cross hair or the x/y axis labels so all I did was add this

**Comment by urbaneg** [comment]
Great. Yeah, we don't do this but I could see how it would be helpful in the future. Sounds like a good update

**Pull request merged**
