### PR TITLE
Show colors of the traces in the list widget

### PR DESCRIPTION
**Pull request by fanmingyu212**
Addresses #16. For each trace, the text in the list widget shows "trace_name - color". There is also an option  (use_trace_color, default False) in updated GUIConfig to show the text in the color of the trace.

The corresponding texts will update when the colors of the traces are changed.

### CODE REVIEW

**Comment by aransfor** [comment]
@fanmingyu212 I cant pull this to check it out. Do you have a fork somewhere?

**Comment by fanmingyu212** [comment]
@aransfor My fork is here: https://github.com/fanmingyu212/RealSimpleGrapher. The branch of this PR is https://github.com/fanmingyu212/RealSimpleGrapher/tree/mf/color_coding_plots.

**Comment by fanmingyu212** [comment]
@aransfor Did you take a look at the code? Please let me know if you cannot access the branch or if you want any change to be made.

**Comment by fanmingyu212** [comment]
Closing this PR (branch in another folked repo) now. Going to open another PR with the branch in this repo.

**Pull request closed without merging**
