### PR TITLE
color coding plots

### PR DESCRIPTION
**Pull request by fanmingyu212**
Addresses #16. For each trace, the text in the list widget shows "trace_name - color". There is also an option (use_trace_color, default False) in updated GUIConfig to show the text in the color of the trace.

The corresponding texts will update when the colors of the traces are changed.

PR (#17) addressed this issue too. I closed #17 because #17 compares to a branch in another folked repo.

### CODE REVIEW

**Comment by aransfor** [comment]
@fanmingyu212 check out these changes.. I think i made some terrible git errors(merging into your branch) so ignore the changes to the rest of the code but see if this color scheming works better. It seems more intuitive on our end to have the color of the text change. email me if you need further info

**Comment by fanmingyu212** [comment]
@aransfor I made a few changes on this branch. The main change I made is to make coloring the trace optional. It can be toggled on/off by setting self.use_trace_color in traceListConfig() in GUIConfig.py. I found it hard to read the trace name on our computers when the trace color is red or magenta. Could it be possible that we substitute those two colors with other colors, for example, light red and light magenta?

**Comment by fanmingyu212** [comment]
@aransfor I also had to add the following code in GUIConfig.py to let the rsg,py run:

        self.isHist = False
        self.vline = False
        self.vline_param = False
        self.hline = False
        self.hline_param = False
        self.line_param = False

Could you update GUIconfig.py.example with the correct (default) configurations for those parameters?

**Comment by fanmingyu212** [comment]
@aransfor Please let me know what you think about the latest commits on color change. I changed red and magenta lighter. I think it will make the labels a little bit easier to read. Also I updated GUIConfig.py.example with the GUIConfig.py I am using now. Could you check if they are the correct default values?

**Comment by aransfor** [comment]
@fanmingyu212 for sure, the hold up is that this isnt working for histograms, I havent had time to find a good fix yet

**Comment by aransfor** [comment]
@fanmingyu212 ok I fixed the histogram. I checked everything I could but we should wait for @urbaneg to pull this and try it out to make sure nothing breaks

**Review by aransfor — APPROVED** [review]
LGTM I like the functionality lots of changes so final ok from @urbaneg before merge

**Comment by urbaneg** [comment]
This is really nice. The only issue I see is that the color becomes white when a trace is highlighted. Also, if you toggle the colors after a scan has run, the labeling color changes but the color of the graph does not. I believe this was already a problem but it might be nice to fix now since you've already incorporated it into the 'select color' option.

**Comment by urbaneg** [comment]
Actually, my mistake. It looks like changing the colors post scan has some bugs for both the 'select color' and 'toggle color' options. Either way, its a problem that already exists and doesn't effect the functionality of this branch.  We should merge.

**Comment by aransfor** [comment]
@urbaneg we fixed the bug for colors changing after the plot is done (ours now change after a plot is complete). If you get a chance could you run RSG in a terminal window and post the error when you toggle colors, I suspect this is a quick fix since we dont have this problem.

**Comment by urbaneg** [comment]
@aransfor There is no error.  I think it is an indexing problem. After the scan has run, if you toggle colors the line connecting to points changes but the markers don't. After that, they both change however the markers are one color in the cycle behind the line.  Something similar happens for color selection.

**Pull request merged**
