### PR TITLE
Amr/histogram

### PR DESCRIPTION
**Pull request by aransfor**
The grapher now can plot histograms and a dragable vertical bar can be tied to a parameter vault variable. This is currently how we set our state detection histograms

### CODE REVIEW

**Comment by aransfor** [comment]
@urbaneg bump on this

**Comment by urbaneg** [comment]
Sorry, I've been out of town. It seems natural to move state detection into the grapher. How does this interact with the 'current' tab? Do you use that functionality?

**Comment by aransfor** [comment]
I do not use the 'current' tab though I may in the future. We use a tab I named 'StateReadout' and in the grapher config file I just tie it to the parameter vault parameter (StateDetection, state_readout_threshold).

e.g. 

    gridGraphConfig('StateReadout', [graphConfig('Histogram', isHist= True, vline='StateReadout Threshold: ',
                                                 vline_param=('StateDetection','state_readout_threshold'),
                                                 show_points = True, grid_on=True, max_datasets=2), 0,0,
                                      graphConfig('Fidelity', show_points=False, grid_on=True,
                                                  isScrolling=True, max_datasets=1), 1, 0,])

**Comment by aransfor** [comment]
This actually allows you to tie parameters to draggable lines in any plot. we now use this for drift tracking and marking pi times and such so we dont have to type it into scriptscanner

**Comment by urbaneg** [comment]
Yeah I like it a lot. And it shouldn't mess with the current tab and if it does, I'll fix it. Shouldn't be too hard. We're good to merge from our end.

**Pull request merged**
